"""Build steps for the frontend.

1. frontend/sample-data.js   — data/sample_leads.csv wrapped as a JS string, so the
                               "Load sample export" button works with no server.
2. dist/index.html           — one self-contained file (CSS + JS inlined) for static
                               hosting: GitHub Pages, S3 + CloudFront, or a demo link.

    python scripts/build.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONT = ROOT / "frontend"
DIST = ROOT / "dist"


def build_sample() -> None:
    csv = (ROOT / "data" / "sample_leads.csv").read_text(encoding="utf-8")
    (FRONT / "sample-data.js").write_text(
        "// Generated by scripts/build.py from data/sample_leads.csv. Synthetic data.\n"
        f"window.TRIAGE_SAMPLE_CSV = {json.dumps(csv)};\n",
        encoding="utf-8",
    )


def build_standalone(api_base: str = "") -> Path:
    html = (FRONT / "index.html").read_text(encoding="utf-8")
    css = (FRONT / "styles.css").read_text(encoding="utf-8")
    html = html.replace('<link rel="stylesheet" href="styles.css">', f"<style>\n{css}\n</style>")

    def inline(match: re.Match) -> str:
        name = match.group(1)
        if name == "config.js":
            body = f"window.TRIAGE_API_BASE = window.TRIAGE_API_BASE || {json.dumps(api_base)};"
        else:
            body = (FRONT / name).read_text(encoding="utf-8")
        return f"<script>\n{body.replace('</script', '<\\/script')}\n</script>"

    html = re.sub(r'<script src="([\w.-]+\.js)"></script>', inline, html)
    DIST.mkdir(exist_ok=True)
    out = DIST / "index.html"
    out.write_text(html, encoding="utf-8")
    return out


if __name__ == "__main__":
    import sys

    build_sample()
    out = build_standalone(sys.argv[1] if len(sys.argv) > 1 else "")
    print(f"wrote frontend/sample-data.js and {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")
